package com.yourwatchrental.watchrental.email;

import com.yourwatchrental.watchrental.rental.dto.response.RentalResponseDTO;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import org.springframework.mail.MailException;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class EmailService {
    private static final String FROM_EMAIL = "kontakt@yourwatchrental.pl";
    private static final String SUPPORT_EMAIL = "kontakt@yourwatchrental.pl";

    private final JavaMailSender mailSender;

    public void sendEmail(String to, RentalResponseDTO response) {

        MimeMessage message = mailSender.createMimeMessage();

        try {
            MimeMessageHelper helper = new MimeMessageHelper(message, false, "UTF-8");

            String text = """
                <html>
                <body>

                    <div style="background-color:#f3f4f6; border:1px solid #d1d5db; padding:16px; margin-bottom:24px;">
                        <h3 style="margin-top:0;">Portfolio Demonstration Project</h3>
                        <p style="margin-bottom:0;">
                            This email was generated by a portfolio demonstration application.
                            All accounts, rentals, and transactions are simulated.
                            Please do not provide any real or sensitive personal information.
                        </p>
                    </div>

                    <h2>New Rental</h2>

                    <p>Hello <strong>%s</strong>,</p>

                    <p>
                        A new rental has been created at your branch.
                    </p>

                    <h3>Customer</h3>

                    <p>
                        <strong>Name:</strong> %s %s<br>
                        <strong>Phone:</strong> %s
                    </p>

                    <h3>Watch</h3>

                    <p>
                        <strong>Brand:</strong> %s<br>
                        <strong>Model:</strong> %s<br>
                        <strong>Serial number:</strong> %s
                    </p>

                    <h3>Rental details</h3>

                    <p>
                        <strong>Rental period:</strong><br>
                        From %s to %s
                    </p>

                    <p>
                        <strong>Payment method:</strong> %s<br>
                        <strong>Created:</strong> %s
                    </p>

                    <hr>

                    <p>
                        This is an automatic notification from
                        <strong>YourWatchRental</strong>.
                    </p>

                    <p>
                        If you have any questions, please contact us at
                        <strong>%s</strong>.
                    </p>

                    <p>
                        Best regards,<br>
                        <strong>The YourWatchRental Team</strong>
                    </p>

                </body>
                </html>
                """.formatted(
                    response.branch().name(),
                    response.user().firstName(),
                    response.user().lastName(),
                    formatPhoneNumber(response.user().phoneNumber()),
                    response.watch().manufacturer(),
                    response.watch().model(),
                    response.watch().serialNumber(),
                    response.startDate(),
                    response.endDate(),
                    response.paymentMethod(),
                    response.createdAt(),
                    SUPPORT_EMAIL
            );

            helper.setFrom(FROM_EMAIL);
            helper.setTo(to);
            helper.setSubject("New Rental - YourWatchRental");
            helper.setText(text, true);

            mailSender.send(message);

        } catch (MessagingException | MailException e) {
            throw new EmailSendException();
        }
    }

    public void sendRentalConfirmationEmail(String to, RentalResponseDTO response) {

        MimeMessage message = mailSender.createMimeMessage();

        try {
            MimeMessageHelper helper = new MimeMessageHelper(message, false, "UTF-8");

            String text = """
                <html>
                <body>

                    <div style="background-color:#f3f4f6; border:1px solid #d1d5db; padding:16px; margin-bottom:24px;">
                        <h3 style="margin-top:0;">Portfolio Demonstration Project</h3>
                        <p style="margin-bottom:0;">
                            This email was generated by a portfolio demonstration application.
                            All accounts, rentals, and transactions are simulated.
                            Please do not provide any real or sensitive personal information.
                        </p>
                    </div>

                    <h2>Rental Confirmation</h2>

                    <p>
                        Hello <strong>%s</strong>,
                    </p>

                    <p>
                        Your watch rental has been successfully created.
                        Here are the details of your rental:
                    </p>

                    <h3>Watch</h3>

                    <p>
                        <strong>Brand:</strong> %s<br>
                        <strong>Model:</strong> %s<br>
                        <strong>Serial number:</strong> %s
                    </p>

                    <h3>Rental details</h3>

                    <p>
                        <strong>Branch:</strong> %s<br>
                        <strong>Rental period:</strong><br>
                        From %s to %s<br>
                        <strong>Payment method:</strong> %s
                    </p>

                    <hr>

                    <p>
                        Please keep this email for your records.
                    </p>

                    <p>
                        If you have any questions or need assistance,
                        please contact us at
                        <strong>%s</strong>.
                    </p>

                    <p>
                        Best regards,<br>
                        <strong>The YourWatchRental Team</strong>
                    </p>

                </body>
                </html>
                """.formatted(
                    response.user().firstName(),
                    response.watch().manufacturer(),
                    response.watch().model(),
                    response.watch().serialNumber(),
                    response.branch().name(),
                    response.startDate(),
                    response.endDate(),
                    response.paymentMethod(),
                    SUPPORT_EMAIL
            );

            helper.setFrom(FROM_EMAIL);
            helper.setTo(to);
            helper.setSubject("Rental Confirmation - YourWatchRental");
            helper.setText(text, true);

            mailSender.send(message);

        } catch (MessagingException | MailException e) {
            throw new EmailSendException();
        }
    }

    public void sendWelcomeEmail(String to, String firstName) {

        MimeMessage message = mailSender.createMimeMessage();

        try {
            MimeMessageHelper helper = new MimeMessageHelper(message, false, "UTF-8");

            String text = """
                <html>
                <body>

                    <div style="background-color:#f3f4f6; border:1px solid #d1d5db; padding:16px; margin-bottom:24px;">
                        <h3 style="margin-top:0;">Portfolio Demonstration Project</h3>
                        <p style="margin-bottom:0;">
                            This website and email are part of a portfolio demonstration project.
                            All accounts, rentals, and transactions are simulated.
                            Please do not provide any real or sensitive personal information.
                        </p>
                    </div>

                    <h2>Welcome to YourWatchRental!</h2>

                    <p>
                        Hello <strong>%s</strong>,
                    </p>

                    <p>
                        Thank you for creating an account with
                        <strong>YourWatchRental</strong>.
                    </p>

                    <p>
                        Your account has been successfully created and
                        you can now log in to the platform and explore
                        our available watches.
                    </p>

                    <p>
                        We hope you enjoy using YourWatchRental.
                    </p>

                    <hr>

                    <p>
                        If you have any questions or need assistance,
                        please contact us at
                        <strong>%s</strong>.
                    </p>

                    <p>
                        Best regards,<br>
                        <strong>The YourWatchRental Team</strong>
                    </p>

                </body>
                </html>
                """.formatted(
                    firstName,
                    SUPPORT_EMAIL
            );

            helper.setFrom(FROM_EMAIL);
            helper.setTo(to);
            helper.setSubject("Welcome to YourWatchRental");
            helper.setText(text, true);

            mailSender.send(message);

        } catch (MessagingException | MailException e) {
            throw new EmailSendException();
        }
    }

    public void sendPasswordResetEmail(String email, String resetUrl) {

        SimpleMailMessage message = new SimpleMailMessage();

        message.setFrom(FROM_EMAIL);
        message.setTo(email);
        message.setSubject("Password Reset - YourWatchRental");

        message.setText("""
            PORTFOLIO DEMONSTRATION PROJECT

            This email was generated by a portfolio demonstration application.
            All accounts, rentals, and transactions are simulated.
            Please do not provide any real or sensitive personal information.

            ---

            Hello,

            We received a request to reset your YourWatchRental password.

            Click the link below to create a new password:

            %s

            This link will expire in 15 minutes.

            If you did not request a password reset, you can safely ignore this email.

            If you need assistance, please contact us at:
            %s

            Best regards,
            The YourWatchRental Team
            """.formatted(
                resetUrl,
                SUPPORT_EMAIL
        ));

        mailSender.send(message);
    }

    private String formatPhoneNumber(String phoneNumber) {

        if (phoneNumber == null) {
            return "Not provided";
        }

        return phoneNumber.replaceAll(
                "(\\d{3})(\\d{3})(\\d{3})",
                "$1-$2-$3"
        );
    }
}
