spring.application.name=watchrental

spring.datasource.url=jdbc:postgresql://localhost:5432/yourwatchrental
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.password-reset.secret=${JWT_SECRET_PASSWORD}
app.password-reset.expiration-minutes=15

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

app.frontend-url=https://yourwatchrental.pl

jwt.secret=${JWT_SECRET}
jwt.expiration=345600000
# 4 days

spring.mail.host=smtp.mail.ovh.net
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true